version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    labels:
      - "github-action dependencies"
      - "bot"
  - package-ecosystem: "pip"
    directory: "/task01"
    schedule:
      interval: "daily"
      time: "04:02"
    allow:
      - dependency-name: "ansible"
        dependency-type: "production"
    labels:
      - "pip dependencies"
      - "bot"
