version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:00"
    labels:
      - "github-action dependencies"
      - "bot"
  - package-ecosystem: "pip"
    directory: "/task01"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:02"
    allow:
      - dependency-name: "ansible"
    ignore:
      - dependency-name: "ansible"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "pip dependencies"
      - "bot"
  - package-ecosystem: "pip"
    directory: "/task02"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:02"
    labels:
      - "pip dependencies"
      - "bot"
  - package-ecosystem: "pip"
    directory: "/task03"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:02"
    labels:
      - "pip dependencies"
      - "bot"
  - package-ecosystem: "pip"
    directory: "/task04"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:02"
    labels:
      - "pip dependencies"
      - "bot"
  - package-ecosystem: "pip"
    directory: "/task07"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:02"
    ignore:
      - dependency-name: "fastapi"
    labels:
      - "pip dependencies"
      - "bot"
  - package-ecosystem: "docker"
    directory: "/task07/docker/app"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:04"
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "docker dependencies"
      - "bot"
  - package-ecosystem: "docker"
    directory: "/task07/docker/test"
    reviewers:
      - "titanlien"
    schedule:
      interval: "daily"
      time: "04:04"
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "docker dependencies"
      - "bot"
