# you can delete this line if you're not using Docker
stages:
  - build
  - test
  - release
  - deploy

image: busybox:latest

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  variables:
    CONTAINER_TEST_IMAGE: $DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/web:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/web:lastest
  services:
    - docker:dind
  before_script:
    - echo $CONTAINER_TEST_IMAGE
    - echo "$CONTAINER_TEST_IMAGE"
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE ./task3/web1/
    - docker push $CONTAINER_TEST_IMAGE
  except:
    - master

test1:
  stage: test
  script:
    - echo "Do a test here"

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
  only:
    - master
