# you can delete this line if you're not using Docker
stages:
  - build
  - test
  - deploy

image: busybox:latest

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" ./task3/web1/
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

test1:
  stage: test
  script:
    - echo "Do a test here"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
