repos:
  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.2.1
    hooks:
    - id: jupyter-notebook-cleanup
      args:
        - --pin-patterns
        - "[pin];[donotremove]"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
