---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: web1
  replicas: 2
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: webapp
          image: titanlien/webapp:1
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: web1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: web1
