---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-2
spec:
  selector:
    matchLabels:
      app: web-2
  replicas: 2
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: web-2
    spec:
      containers:
        - name: webapp
          image: titanlien/webapp2:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-2
  labels:
    app: web-2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: web-2
