---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-1
spec:
  selector:
    matchLabels:
      app: web-1
  replicas: 2
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: web-1
    spec:
      containers:
        - name: webapp
          image: titanlien/webapp1:v2
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webap-1
  labels:
    app: web-1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: web-1
