---
- hosts: all
  roles:
    - role: geerlingguy.java
      become: yes
  tasks:
    - name: Upload systemctl configure file
      copy:
        src: task1.service
        dest: /etc/systemd/system/task1.service
      register: upload_systemctl_config

    - name: Reload systemctl
      systemd:
        name: task1
        daemon_reload: yes
        state: started
      when: upload_systemctl_config
