---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app.kubernetes.io/version: "1.16.0"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: tree
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app.kubernetes.io/version: "1.16.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tree
  template:
    metadata:
      labels:
        app: tree
        version: dev
    spec:
      containers:
        - name: tree
          image: "tree:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /tree
              port: http
          readinessProbe:
            httpGet:
              path: /tree
              port: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp
  labels:
    app.kubernetes.io/version: "1.16.0"
    app: tree
spec:
  rules:
    - host: "local.ecosia.org"
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 5000
