version: '3.4'

services:
  nginx:
    image: nginx:stable
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
    - 80:80
    depends_on:
    - webapp-1

    restart: always
  webapp-1:
    image: webapp
    build:
      context: .
      dockerfile: webapp/Dockerfile
