name: Build and push webapp image

on:
  push:
    branches:
      - master
      - dev

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: >
          docker-compose
          -f docker-compose.yml
          -f docker-compose.test.yml
          up
          --abort-on-container-exit

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get short SHA
        uses: benjlevesque/short-sha@v.1.1
        id: short-sha
        with:
          length: 7
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Publish Image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          registry: docker.pkg.github.com
          name: ${{ github.repository }}/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: "${{ env.SHA }},${{ env.BRANCH_NAME }}"
          dockerfile: docker/app/Dockerfile
          workdir: .
