apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: webapp
        image: docker.pkg.github.com/titanlien/workshop/web1:master
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
            httpGet:
               path: /
               port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
