name: Build and Push docker image

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Docker Action
      uses: matootie/github-docker@v2.2.1
      with:
        accessToken: ${{secrets.GITHUB_TOKEN}}
        context: ./task3/web1/
        username: $GITHUB_ACTOR
        imageName: web1
        imageTag: $GITHUB_SHA
