name: Build and Push docker image

on: [push]
env:
  DOCKER_REGISTRY: docker.pkg.github.com

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: |
          docker login \
            --username $GITHUB_ACTOR \
            --password ${{secrets.GITHUB_TOKEN}} \
            docker.pkg.github.com

    - name: build webapp1 image
      run: |
          cd task3 && \
          docker build -t $DOCKER_REGISTRY/$GITHUB_REPOSITORY/webapp1:$GITHUB_SHA \
                     --file web1/Dockerfile \
                     ./web1/
                     
    - name: build webapp2 image
      run: |
          cd task3 && \
          docker build -t $DOCKER_REGISTRY/$GITHUB_REPOSITORY/webapp2:$GITHUB_SHA \
                     --file web2/Dockerfile \
                     ./web2/
                     

    - name: Deploy
      run: |
          docker push $DOCKER_REGISTRY/$GITHUB_REPOSITORY/webapp1:$GITHUB_SHA &&\
          docker push $DOCKER_REGISTRY/$GITHUB_REPOSITORY/webapp2:$GITHUB_SHA
