name: Build and Push docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Docker Action
      uses: matootie/github-docker@v2.2.1
      with:
        accessToken: ${{secrets.GITHUB_TOKEN}}
        context: ./task03/web1/
        imageName: web1
    - name: GitHub Docker Action
      uses: matootie/github-docker@v2.2.1
      with:
        accessToken: ${{secrets.GITHUB_TOKEN}}
        context: ./task03/web2/
        imageName: web2
