name: Task03 Build and Push docker image

on:
  push:
    branches:
      - master
    paths:
      - 'task03/**'
  pull_request:
    paths:
      - 'task03/**'
    branches:
      - master
  release:
    paths:
      - 'task03/**'
    types:
      - created

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: GitHub Docker Action
      uses: matootie/github-docker@v3.1.0
      id: publish-web1
      with:
        accessToken: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        context: ./task03/web1/
        imageName: task03-web1
    - name: GitHub Docker Action
      uses: matootie/github-docker@v3.1.0
      id: publish-web2
      with:
        accessToken: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        context: ./task03/web2/
        imageName: task03-web2
