name: Task07 build and push webapp image

on:
  pull_request:
    types: [closed]
    paths:
      - 'task07/**'
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - 'task07/**'

defaults:
  run:
    working-directory: task07

jobs:
  build:
    name: Task07 Build and push docker image
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get short SHA
        uses: benjlevesque/short-sha@v.1.1
        id: short-sha
        with:
          length: 7
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Publish Image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          registry: docker.pkg.github.com
          name: ${{ github.repository }}/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          tags: "${{ env.SHA }},${{ env.BRANCH_NAME }}"
          dockerfile: docker/app/Dockerfile
          workdir: .
